#!/bin/bash

sudo chmod +x /usr/libexec/fbmenuctl_gui.py

help() {
	echo "Usage: fbmenuctl [options]"
	echo "Options:"
	echo "	-h	--help		Show the help message"
	echo "	--set-menu [PATH]	Set the menu file to [PATH]"
	echo "	--list-menus		Display all valid menu files"
}

while [[ $# -gt 0 ]] do
	case "$1" in
		-h|--help)
			help
			exit 0
			;;
		--set-menu)
			if [ -z $2 ]; then
				echo "ERROR: No argument provided for '--set-menu'"
				exit 0
			fi
			if [ -f $2 ]; then
				sed -i "s|^session\.menuFile:.*|session.menuFile: $2|" "$HOME/.fluxbox/init"
				echo "Menu succesfully updated to $2"
				fluxbox-remote restart
				exit 0
			else
				echo "$2 not found."
				exit 0
			fi
			;;
		--list-menus)
			find "$HOME/.fluxbox" -name menu*
			exit 0
			;;
		*)
			echo "ERROR: Not a valid argument"
			;;
	esac
done

python3 /usr/libexec/fbmenuctl_gui.py
